import { writeFileSync } from 'node:fs';
const js = await (await fetch('http://127.0.0.1:8124/pkg/multi_cpu_emu.js')).text();
writeFileSync('/tmp/opencode/pkgmod11.mjs', js);
const mod = await import('file:///tmp/opencode/pkgmod11.mjs?x=' + Date.now());
const wasmBytes = new Uint8Array(await (await fetch('http://127.0.0.1:8124/pkg/multi_cpu_emu_bg.wasm')).arrayBuffer());
await mod.default(wasmBytes);
const { Emulator } = mod;
const e = new Emulator("8086");
const src = "ORG 100h\nMOV AL, 42h\nOUT 03h, AL\nMOV AL, 00h\nIN AL, 03h\nMOV DX, 0005h\nOUT DX, AL\nMOV AH, 4Ch\nINT 21h\nEND";
e.load(e.assemble(src), 0);
e.run(1000);
console.log("8086: AL =", e.regs()[0], "| port3 =", e.port_read(3).toString(16), "| port5 =", e.port_read(5).toString(16));
e.port_write(9, 0x77); console.log("port9 write =", e.port_read(9).toString(16));
const m = new Emulator("8051");
const s51 = "MOV P1, #00h\nMOV A, P1\nMOV R0, A\nSJMP $\nEND";
m.port_write(1, 0x55);
m.load(m.assemble(s51), 0);
m.run(100);
console.log("8051: A =", m.regs()[0].split('=')[1]);
