/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const __wbg_emulator_free: (a: number, b: number) => void;
export const emulator_assemble: (a: number, b: number, c: number) => [number, number, number, number];
export const emulator_assemble_info: (a: number, b: number, c: number) => [number, number, number, number];
export const emulator_flags: (a: number) => [number, number];
export const emulator_fs_get: (a: number, b: number, c: number) => [number, number, number, number];
export const emulator_fs_put: (a: number, b: number, c: number, d: number, e: number) => [number, number];
export const emulator_halted: (a: number) => number;
export const emulator_interrupt: (a: number, b: number, c: number, d: number) => [number, number];
export const emulator_load: (a: number, b: number, c: number, d: number) => void;
export const emulator_mem: (a: number, b: number, c: number) => [number, number];
export const emulator_mem_write: (a: number, b: number, c: number, d: number) => void;
export const emulator_new: (a: number, b: number) => [number, number, number];
export const emulator_out: (a: number) => [number, number];
export const emulator_pc: (a: number) => number;
export const emulator_port_read: (a: number, b: number) => number;
export const emulator_port_write: (a: number, b: number, c: number) => void;
export const emulator_push_key: (a: number, b: number) => void;
export const emulator_regs: (a: number) => [number, number];
export const emulator_reset: (a: number) => void;
export const emulator_restore: (a: number, b: number, c: number) => void;
export const emulator_run: (a: number, b: number) => number;
export const emulator_run_bp: (a: number, b: number, c: number, d: number) => number;
export const emulator_run_to: (a: number, b: number, c: number) => number;
export const emulator_serial_rx: (a: number, b: number) => [number, number];
export const emulator_set_clock: (a: number, b: number, c: number, d: number, e: number, f: number, g: number) => [number, number];
export const emulator_set_pc: (a: number, b: number) => void;
export const emulator_set_sid: (a: number, b: number) => void;
export const emulator_snapshot: (a: number) => [number, number];
export const emulator_sod: (a: number) => number;
export const emulator_step: (a: number) => void;
export const emulator_waiting_input: (a: number) => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __externref_drop_slice: (a: number, b: number) => void;
export const __wbindgen_start: () => void;
